import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="page-container" style={{ background: 'var(--bg-base)' }}>
      <nav className="landing-nav">
        <div className="brand-logo">GestureAI</div>
        <Link href="/" className="back-link"><ArrowLeft size={16} /> Back to Home</Link>
      </nav>
      
      <main className="content-wrapper">
        <h1 className="page-title">Privacy Architecture</h1>
        <div className="prose">
          <h2>Absolute Edge Processing Guarantee</h2>
          <p>GestureAI utilizes client-side WebGL and neural network inference. This architectural choice means your raw camera feed, biometric data, and physical kinematics are processed <strong>entirely within the memory of your local device</strong>.</p>
          
          <h2>Zero Transmission Protocol</h2>
          <p>We do not operate backend servers for video processing. We do not upload, store, cache, or transmit your camera feed anywhere. The spatial coordinates generated by your gestures exist only milliseconds at a time in your browser tab, and are immediately destroyed after rendering.</p>
          
          <h2>Analytics & Telemetry</h2>
          <p>To maintain industrial-grade stability, we may collect fully anonymized telemetry (such as crash logs and page load speeds). This data contains zero personal identifiers and cannot be linked back to individual users.</p>
        </div>
      </main>
    </div>
  );
}
